// Localidades de la provincia de La Pampa, Argentina: los 61 municipios,
// las 18 comisiones de fomento y la comuna de Casa de Piedra.
// Fuente: Gobierno de la Provincia de La Pampa (lapampa.gob.ar).
const RAW_CITIES = [
  "Abramo",
  "Adolfo Van Praet",
  "Agustoni",
  "Algarrobo del Águila",
  "Alpachiri",
  "Alta Italia",
  "Anguil",
  "Arata",
  "Ataliva Roca",
  "Bernardo Larroudé",
  "Bernasconi",
  "Caleufú",
  "Carro Quemado",
  "Casa de Piedra",
  "Catriló",
  "Ceballos",
  "Chacharramendi",
  "Colonia Barón",
  "Colonia Santa María",
  "Conhello",
  "Coronel Hilario Lagos",
  "Cuchillo Có",
  "Doblas",
  "Dorila",
  "Eduardo Castex",
  "Embajador Martini",
  "Falucho",
  "General Acha",
  "General Manuel Campos",
  "General Pico",
  "General San Martín",
  "Gobernador Duval",
  "Guatraché",
  "Ingeniero Luiggi",
  "Intendente Alvear",
  "Jacinto Arauz",
  "La Adela",
  "La Humada",
  "La Maruja",
  "La Reforma",
  "Limay Mahuida",
  "Lonquimay",
  "Loventuel",
  "Luan Toro",
  "Macachín",
  "Maisonnave",
  "Mauricio Mayer",
  "Metileo",
  "Miguel Cané",
  "Miguel Riglos",
  "Monte Nievas",
  "Parera",
  "Perú",
  "Pichi Huinca",
  "Puelches",
  "Puelén",
  "Quehué",
  "Quemú Quemú",
  "Quetrequén",
  "Rancul",
  "Realicó",
  "Relmo",
  "Rolón",
  "Rucanelo",
  "Santa Isabel",
  "Santa Rosa",
  "Santa Teresa",
  "Sarah",
  "Speluzzi",
  "Telén",
  "Toay",
  "Tomás Manuel Anchorena",
  "Trenel",
  "25 de Mayo",
  "Unanue",
  "Uriburu",
  "Vértiz",
  "Victorica",
  "Villa Mirasol",
  "Winifreda",
];

export const LA_PAMPA_CITIES: string[] = [...RAW_CITIES].sort((a, b) =>
  a.localeCompare(b, "es")
);
